site_name: Game Developer's Library
theme:
  name: material
  palette: 

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: deep purple
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
    
  features:
    - content.code.copy
    - content.code.annotate
  
  plugins:
    - optimize

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.keys

# Do not touch anything above here!

# Here is where you can route new pages
nav:
  - Home: 'index.md'
  - Tutorials:
    - 'Tutorials Index': 'tutorials/tutorials-index.md'
    - Unity Tutorials:
      - 'Introduction to the Editor': 'tutorials/unity-tutorials/unity-editor-introduction.md'
      - First Steps:
        - 'Introduction': 'tutorials/unity-tutorials/first-step-series/unity-first-step-index.md'
        - 'Install Unity': 'tutorials/unity-tutorials/first-step-series/unity-first-step-install.md'
        - 'Create a New Project': 'tutorials/unity-tutorials/first-step-series/unity-first-step-new-proj.md'
        - 'Rocket Runner Base': 'tutorials/unity-tutorials/first-step-series/unity-runner-1.md'
  - Guides:
    - 'Guide Index': 'guides/guides-index.md'

  - Articles:
    - 'Article Index': 'articles/articles-index.md'
    - 'Unity Articles':
      - 'Unity Overview': 'articles/unity-articles/unity-overview.md'
      - 'Scriptable Render Pipelines': 'articles/unity-articles/unity-render-pipelines.md'


  - Contribution:
    - 'Using MkDocs': 'contribution/mkdocs-usage.md'
    - 'Making New Pages': 'contribution/making-new-pages.md'