site_name: Game Developer's Library
theme:
  name: material

nav:
  - Home: 'index.md'
  - Guides:
    - 'Guide Index': 'guides/guides-index.md'
    - 'Unity Guides':
      - 'First Step Series':
        - 'Introduction': 'guides/unity-guides/first-step-series/unity-first-step-index.md'
        - 'Install Unity': 'guides/unity-guides/first-step-series/unity-first-step-install.md'
        - 'Create a New Project': 'guides/unity-guides/first-step-series/unity-first-step-new-proj.md'
  - Articles:
    - 'Article Index': 'articles/articles-index.md'
    - 'Unity Articles':
      - 'Project Type Capabilities': 'articles/unity-articles/unity-type-capabilities.md'
      - 'Introduction to the Editor': 'articles/unity-articles/unity-editor-introduction.md'
      - 'Scriptable Render Pipelines': 'articles/unity-articles/unity-render-pipelines.md'
  - Contribution:
    - 'Using MkDocs': 'contribution/mkdocs-usage.md'
    - 'Making New Pages': 'contribution/making-new-pages.md'